import RootLayoutClient from "./root-layout-client"; 
import Sidebar from "@/components/sidebar";

export const metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="flex min-h-screen">
      <div className="flex-1 bg-gray-100 p-6">
    <RootLayoutClient>{children}</RootLayoutClient>
       </div>
      <div className="w-64 bg-gray-800 text-white">
        <Sidebar />
         </div>
      </body>
    </html>
  );
}
